# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-29 01:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '\u6587\u7ae0\u4fe1\u606f', 'verbose_name_plural': '\u6587\u7ae0\u4fe1\u606f'},
        ),
    ]
