# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-29 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180329_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(verbose_name='\u6b63\u6587'),
        ),
    ]
